ChatRoom/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('openchat.urls'))
]

openchat/urls.py
from django.conf.urls import url
from . import views


app_name = 'openchat'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^chat/$', views.chat, name='chat'),
    # websocket 相关

]

openchat/models.py
from django.db import models
from channels import Group
import json
# Create your models here.


class Room(models.Model):
    """
    聊天室model
    """

    name = models.CharField(
        '房间名字',
        max_length=128,
        default='待编辑'
    )

    def __str__(self):
        return self.name

    @property
    def websocket_group(self):
        '''
        返回一个channels 群组，
        让websocket在其中广播对应的信息
        '''
        return Group('房间id：{}'.format(self.pk))

    def send_message(self, message, user):
        '''
        向该用户所在的房间里发送信息
        '''
        final_msg = {
            'room': str(self.pk),
            'message': message,
            'user': user.username,
        }
        # 发送信息
        self.websocket_group.send(
            {'text': json.dumps(final_msg)}
        )

openchat/views.py
from django.shortcuts import render, render_to_response, redirect
from django.http import HttpResponse
from .models import Room


# Create your views here.
def index(request):
    '''
    渲染聊天室的首页
    '''
    return render(request, 'index.html')


def login(request):
    '''
    获取昵称
    '''
    if request.method == 'POST':
        name = request.POST.get('name', '')
        if name != '':
            request.session['name'] = name
            return redirect('/chat')
        else:
            return HttpResponse('请输入聊天昵称')


def chat(request):
    '''
    聊天页面的封装
    返回当前系统内所有的聊天室
    '''
    rooms = Room.objects.all()
    try:
        name = request.session['name']
        return render(request, 'chat.html', {'rooms': rooms, })
    except:
        return redirect('/index')


# def joined(request):
#     '''
#     当有人进入聊天室之后，会从客户端发送一条加入房间的信息
#     并且这个条信息会向所有在当前频道的人广播
#     '''
#     while True:
#         message = request.websocket.wait()
#         request.websocket.send('return' + message)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <title>匿名聊天室</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- css  -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.1/css/bulma.min.css">
    <!-- js  -->
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script> {% block extra_head %} {% endblock %}
</head>

<body>
    <section class="section">
        <div class="container">
            {% block main %} {% endblock %}
        </div>
    </section>
</body>
</html>

templates/chat.html
{% extends "base.html" %} {% block main %}

<div id='id-div-channels'>
    <h1 class="title" id='id-div-channels-title'>聊天室</h1>

    {% for room in rooms %}
    <a class="rc-channel" href="#">{{ room.title }}</a>
    {% empty %}
    <p>还没有聊天室</p>

    {% endfor %}
</div>
<h1>chat</h1>
<textarea id="id_chat_area" cols="80" rows="20"></textarea>
<br>
<br>
<input id="text" size="80" placeholder="Enter your message here">
<br>
<br> {% endblock %}

templates/index.html
 {% extends "base.html" %} 

{% block main %}
<h1 class="title">
    匿名聊天室
</h1>
<p class="subtitle">
    简单 高效 快速 信息分享
</p>
<form class="form" method="POST" action="{% url 'openchat:login' %}">
    {% csrf_token %}
    <label class="label">输入聊天昵称：</label>
    <input class="input" type=text name="name" placeholder="name">
    <button type="submit" class="button">点击进入！</button>
</form>
{% endblock %}